# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.cl.clcore
canonical: https://hl7chile.cl/fhir/ig/clcore
name: clcore
title: Guía de Implementación cl core FHIR R4, (Versión Evolutiva)
status: draft # draft | active | retired | unknown
version: 2.0.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2024+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: HL7 Chile
  url: http://hl7chile.cl
  email: chair@hl7chile.cl

description: "Guía de Implementación de FHIR R4 para Chile, versión 2.0.0, que contiene los recursos básicos de FHIR necesarios para la interoperabilidad en el contexto chileno. Esta guía es una evolución de la versión 1.0.0, incorporando mejoras y correcciones basadas en la experiencia adquirida en su uso."
jurisdiction: urn:iso:std:iso:3166#CL "Chile"
copyright: "Usado con el permiso de HL7 International, todos los derechos resevados en los Licencias de HL7 Internacional."
license: CC0-1.0


dependencies:
  hl7.fhir.cl.minsal.eis: 0.1.0
pages:
  index.md:
    title: Inicio
  Alcances-Objetivos.md:
    title: Objetivos
  Notas-MS.md:
    title: Notas del Must Support
  Aspectos-Generales.md:
    title: Generalidades
  ImplementationGuide-hl7.fhir.cl.clcore.md:
    title: Recursos ImplementationGuide Cl Core
  #Extensiones.md:
  #Set-De-Validacion-ValueSets.md:
  #  title: CodeSystems/ValueSets
  #Perfiles.md:
  #  title: Perfiles
  #Set-Ejemplos.md:
  #  title: Ejemplos
  changes.md:
    title: Historial de Cambios

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

menu:
  Inicio: index.html
  Objetivos: Alcances-Objetivos.html
  Must Support: Notas-MS.html
  Generalidades: Aspectos-Generales.html
  CapabilityStatement:
    CapabilityStatement Servidor: CapabilityStatement-cl-core-server.html
    CapabilityStatement Cliente: CapabilityStatement-cl-core-client.html
  Artefactos: artifacts.html
    #Perfiles: Perfiles.html
    #Extensiones: Extensiones.html
    #Valuesets: Set-De-Validacion-ValueSets.html
#  Ejemplos: Set-Ejemplos.html
  Historial de cambios: changes.html


parameters:
  apply-publisher: true
  apply-contact: true
  show-inherited-invariants: false
  excludettl: true
  generate: genExamples
  path-resource:
    - input/resources
    - fsh-generated/resources
  path-expansion-params: '../../input/_resources/exp-params.json'
